export const FUND_ADMIN_ABI = [
    {
        inputs: [{ name: 'role', type: 'bytes32' }, { name: 'account', type: 'address' }],
        name: 'hasRole',
        outputs: [{ name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ name: 'role', type: 'bytes32' }, { name: 'account', type: 'address' }],
        name: 'grantRole',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'profitDistributor',
        outputs: [{ name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'liquidityCoordinator',
        outputs: [{ name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'treasury',
        outputs: [{ name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'currentRoundId',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'referenceNavPerTokenUsdt6',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { name: '_positionId', type: 'uint256' },
            { name: '_sourceType', type: 'uint8' },
            { name: '_sourceRef', type: 'bytes32' },
            { name: '_candidateValueUsdt6', type: 'uint256' },
            { name: '_proofHash', type: 'bytes32' },
        ],
        name: 'submitValuationObservation',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ name: '_roundId', type: 'uint256' }],
        name: 'getRound',
        outputs: [
            {
                components: [
                    { name: 'roundId', type: 'uint256' },
                    { name: 'targetAmount', type: 'uint256' },
                    { name: 'raisedAmount', type: 'uint256' },
                    { name: 'tokenPrice', type: 'uint256' },
                    { name: 'minInvestment', type: 'uint256' },
                    { name: 'maxInvestment', type: 'uint256' },
                    { name: 'startTime', type: 'uint256' },
                    { name: 'endTime', type: 'uint256' },
                    { name: 'isActive', type: 'bool' },
                    { name: 'isFinalized', type: 'bool' },
                ],
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { name: '_targetAmount', type: 'uint256' },
            { name: '_tokenPrice', type: 'uint256' },
            { name: '_minInvestment', type: 'uint256' },
            { name: '_maxInvestment', type: 'uint256' },
            { name: '_startTime', type: 'uint256' },
            { name: '_endTime', type: 'uint256' },
        ],
        name: 'createFundraisingRound',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ name: '_roundId', type: 'uint256' }],
        name: 'finalizeRound',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ name: 'adapter', type: 'address' }, { name: 'approved', type: 'bool' }],
        name: 'setApprovedBridgeAdapter',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'purchaseKey', type: 'bytes32' },
            { name: 'tokenIn', type: 'address' },
            { name: 'tokenOut', type: 'address' },
            { name: 'path', type: 'address[]' },
            { name: 'amountOut', type: 'uint256' },
            { name: 'maxAmountIn', type: 'uint256' },
            { name: 'bridgeAdapter', type: 'address' },
            { name: 'dstEid', type: 'uint32' },
            { name: 'dstSafe', type: 'address' },
            { name: 'lzOptions', type: 'bytes' },
        ],
        name: 'swapAndBridge',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { name: '_purchaseKey', type: 'bytes32' },
            { name: '_fundingToken', type: 'address' },
            { name: '_amountUsdt6', type: 'uint256' },
            { name: '_destinationChainEid', type: 'uint32' },
            { name: '_destinationSafe', type: 'address' },
            { name: '_settlementRef', type: 'bytes32' },
            { name: '_proofHash', type: 'bytes32' },
        ],
        name: 'confirmPurchaseFunding',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: '_saleKey', type: 'bytes32' },
            { name: '_proceedsRef', type: 'bytes32' },
            { name: '_proofHash', type: 'bytes32' },
        ],
        name: 'confirmNativeSaleProceeds',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { name: '_saleKey', type: 'bytes32' },
            { name: '_proceedsToken', type: 'address' },
            { name: '_amount', type: 'uint256' },
            { name: '_pullFromCaller', type: 'bool' },
            { name: '_proceedsRef', type: 'bytes32' },
            { name: '_proofHash', type: 'bytes32' },
        ],
        name: 'confirmStableSaleProceeds',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ name: '_saleKey', type: 'bytes32' }],
        name: 'finalizeSale',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: '_token', type: 'address' },
            { name: '_approved', type: 'bool' },
            { name: '_decimals', type: 'uint8' },
        ],
        name: 'setSaleSettlementToken',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ name: 'account', type: 'address' }, { name: 'excluded', type: 'bool' }],
        name: 'setProfitShareExclusion',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: '_to', type: 'address' },
            { name: '_amount', type: 'uint256' },
            { name: '_reason', type: 'string' },
        ],
        name: 'withdrawFromTreasury',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ name: '_purchaseKey', type: 'bytes32' }, { name: '_amountUsdt6', type: 'uint256' }],
        name: 'releasePurchaseFunds',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: '_purchaseKey', type: 'bytes32' },
            {
                components: [
                    { name: 'custodyMode', type: 'uint8' },
                    { name: 'tokenStandard', type: 'bytes32' },
                    { name: 'evmCollection', type: 'address' },
                    { name: 'nonEvmCollection', type: 'bytes32' },
                    { name: 'tokenId', type: 'uint256' },
                    { name: 'nonEvmTokenId', type: 'bytes32' },
                    { name: 'externalAssetId', type: 'bytes32' },
                    { name: 'categoryId', type: 'bytes32' },
                    { name: 'marketplaceProvenanceRef', type: 'bytes32' },
                    { name: 'acquisitionPriceUsdt6', type: 'uint256' },
                    { name: 'metadataHash', type: 'bytes32' },
                    { name: 'proofHash', type: 'bytes32' },
                ],
                name: '_input',
                type: 'tuple',
            },
        ],
        name: 'recordCollectiblePosition',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'stableAccounting',
        outputs: [
            { name: 'canonicalPortfolioValue', type: 'uint256' },
            { name: 'lastStableNavUpdateTimestamp', type: 'uint256' },
            { name: 'liquidTreasury', type: 'uint256' },
            { name: 'outstandingPurchaseReleases', type: 'uint256' },
            { name: 'liquidityCatchBuyAccrued', type: 'uint256' },
            { name: 'liquidityAvaxPairingAccrued', type: 'uint256' },
            { name: 'holderDistributionAccrued', type: 'uint256' },
            { name: 'weeklyNavCap', type: 'uint256' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
] as const;

export const CHAINLINK_AGGREGATOR_V3_ABI = [
    {
        inputs: [],
        name: 'latestRoundData',
        outputs: [
            { name: 'roundId', type: 'uint80' },
            { name: 'answer', type: 'int256' },
            { name: 'startedAt', type: 'uint256' },
            { name: 'updatedAt', type: 'uint256' },
            { name: 'answeredInRound', type: 'uint80' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
] as const;

export const ERC20_ABI = [
    {
        inputs: [{ name: 'account', type: 'address' }],
        name: 'balanceOf',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ name: 'owner', type: 'address' }, { name: 'spender', type: 'address' }],
        name: 'allowance',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ name: 'spender', type: 'address' }, { name: 'amount', type: 'uint256' }],
        name: 'approve',
        outputs: [{ name: '', type: 'bool' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
] as const;

export const WAVAX_ABI = [
    ...ERC20_ABI,
    {
        inputs: [],
        name: 'deposit',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
] as const;

export const LEGACY_JOE_ROUTER_ABI = [
    {
        inputs: [{ name: 'amountIn', type: 'uint256' }, { name: 'path', type: 'address[]' }],
        name: 'getAmountsOut',
        outputs: [{ name: 'amounts', type: 'uint256[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { name: 'amountOutMin', type: 'uint256' },
            { name: 'path', type: 'address[]' },
            { name: 'to', type: 'address' },
            { name: 'deadline', type: 'uint256' },
        ],
        name: 'swapExactAVAXForTokens',
        outputs: [{ name: 'amounts', type: 'uint256[]' }],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'token', type: 'address' },
            { name: 'amountTokenDesired', type: 'uint256' },
            { name: 'amountTokenMin', type: 'uint256' },
            { name: 'amountAVAXMin', type: 'uint256' },
            { name: 'to', type: 'address' },
            { name: 'deadline', type: 'uint256' },
        ],
        name: 'addLiquidityAVAX',
        outputs: [
            { name: 'amountToken', type: 'uint256' },
            { name: 'amountAVAX', type: 'uint256' },
            { name: 'liquidity', type: 'uint256' },
        ],
        stateMutability: 'payable',
        type: 'function',
    },
] as const;

export const PHARAOH_POOL_ABI = [
    {
        inputs: [],
        name: 'slot0',
        outputs: [
            { name: 'sqrtPriceX96', type: 'uint160' },
            { name: 'tick', type: 'int24' },
            { name: 'observationIndex', type: 'uint16' },
            { name: 'observationCardinality', type: 'uint16' },
            { name: 'observationCardinalityNext', type: 'uint16' },
            { name: 'feeProtocol', type: 'uint8' },
            { name: 'unlocked', type: 'bool' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
] as const;

export const PHARAOH_SWAP_ROUTER_ABI = [
    {
        inputs: [
            {
                components: [
                    { name: 'tokenIn', type: 'address' },
                    { name: 'tokenOut', type: 'address' },
                    { name: 'fee', type: 'uint24' },
                    { name: 'recipient', type: 'address' },
                    { name: 'deadline', type: 'uint256' },
                    { name: 'amountIn', type: 'uint256' },
                    { name: 'amountOutMinimum', type: 'uint256' },
                    { name: 'sqrtPriceLimitX96', type: 'uint160' },
                ],
                name: 'params',
                type: 'tuple',
            },
        ],
        name: 'exactInputSingle',
        outputs: [{ name: 'amountOut', type: 'uint256' }],
        stateMutability: 'payable',
        type: 'function',
    },
] as const;

export const PHARAOH_POSITION_MANAGER_ABI = [
    {
        inputs: [
            {
                components: [
                    { name: 'token0', type: 'address' },
                    { name: 'token1', type: 'address' },
                    { name: 'fee', type: 'uint24' },
                    { name: 'tickLower', type: 'int24' },
                    { name: 'tickUpper', type: 'int24' },
                    { name: 'amount0Desired', type: 'uint256' },
                    { name: 'amount1Desired', type: 'uint256' },
                    { name: 'amount0Min', type: 'uint256' },
                    { name: 'amount1Min', type: 'uint256' },
                    { name: 'recipient', type: 'address' },
                    { name: 'deadline', type: 'uint256' },
                ],
                name: 'params',
                type: 'tuple',
            },
        ],
        name: 'mint',
        outputs: [
            { name: 'tokenId', type: 'uint256' },
            { name: 'liquidity', type: 'uint128' },
            { name: 'amount0', type: 'uint256' },
            { name: 'amount1', type: 'uint256' },
        ],
        stateMutability: 'payable',
        type: 'function',
    },
] as const;

export const LIQUIDITY_COORDINATOR_ABI = [
    {
        inputs: [],
        name: 'traderJoeLpDeployedAvaxWei',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'pharaohLpDeployedAvaxWei',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'traderJoeLpTokenDeployed18',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'pharaohLpTokenDeployed18',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
] as const;

export const PROFIT_DISTRIBUTOR_ABI = [
    {
        inputs: [{ name: 'account', type: 'address' }],
        name: 'excludedFromProfitShare',
        outputs: [{ name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ name: 'account', type: 'address' }],
        name: 'claimableProfit',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'eligibleSupply',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'cumulativeProfitPerTokenWei18',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'totalProfitDepositedWei',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
] as const;

export const REGISTRY_ABI = [
    {
        inputs: [
            { name: 'chainEid', type: 'uint32' },
            { name: 'evmSafe', type: 'address' },
            { name: 'nonEvmSafe', type: 'bytes32' },
            { name: 'label', type: 'bytes32' },
            { name: 'enabled', type: 'bool' },
        ],
        name: 'setChainSafe',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ name: 'marketplaceId', type: 'bytes32' }, { name: 'approved', type: 'bool' }],
        name: 'setMarketplaceApproval',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'purchaseKey', type: 'bytes32' },
            { name: 'chainEid', type: 'uint32' },
            { name: 'marketplaceId', type: 'bytes32' },
            { name: 'assetRef', type: 'bytes32' },
            { name: 'maxSpendUsdt6', type: 'uint256' },
            { name: 'mandateHash', type: 'bytes32' },
        ],
        name: 'authorizePurchase',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'purchaseKey', type: 'bytes32' },
            { name: 'chainEid', type: 'uint32' },
            { name: 'marketplaceId', type: 'bytes32' },
            { name: 'assetRef', type: 'bytes32' },
            { name: 'fundingToken', type: 'address' },
            { name: 'maxSpendUsdt6', type: 'uint256' },
            { name: 'mandateHash', type: 'bytes32' },
        ],
        name: 'authorizePurchaseV2',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'purchaseKey', type: 'bytes32' },
            { name: 'executionRef', type: 'bytes32' },
            { name: 'settlementRef', type: 'bytes32' },
            { name: 'proofHash', type: 'bytes32' },
        ],
        name: 'recordPurchaseExecution',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'saleKey', type: 'bytes32' },
            { name: 'positionId', type: 'uint256' },
            { name: 'marketplaceId', type: 'bytes32' },
            { name: 'minNetProceedsUsdt6', type: 'uint256' },
            { name: 'mandateHash', type: 'bytes32' },
        ],
        name: 'authorizeSale',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'saleKey', type: 'bytes32' },
            { name: 'grossProceedsUsdt6', type: 'uint256' },
            { name: 'marketplaceFeesUsdt6', type: 'uint256' },
            { name: 'bridgeFeesUsdt6', type: 'uint256' },
            { name: 'executionRef', type: 'bytes32' },
            { name: 'proceedsRef', type: 'bytes32' },
            { name: 'proofHash', type: 'bytes32' },
        ],
        name: 'recordSaleExecution',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'saleKey', type: 'bytes32' },
            { name: 'sourceChainEid', type: 'uint32' },
            { name: 'sourceToken', type: 'address' },
            { name: 'sourceTokenAmount', type: 'uint256' },
            { name: 'sourceTokenDecimals', type: 'uint8' },
            { name: 'sourceProceedsRef', type: 'bytes32' },
            { name: 'proofHash', type: 'bytes32' },
        ],
        name: 'recordExternalSaleProceeds',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'collectiblePositionCount',
        outputs: [{ name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ name: 'positionId', type: 'uint256' }],
        name: 'getCollectiblePosition',
        outputs: [
            {
                components: [
                    { name: 'id', type: 'uint256' },
                    { name: 'originPurchaseKey', type: 'bytes32' },
                    { name: 'chainEid', type: 'uint32' },
                    { name: 'marketplaceId', type: 'bytes32' },
                    { name: 'custodyMode', type: 'uint8' },
                    { name: 'tokenStandard', type: 'bytes32' },
                    { name: 'evmCollection', type: 'address' },
                    { name: 'nonEvmCollection', type: 'bytes32' },
                    { name: 'tokenId', type: 'uint256' },
                    { name: 'nonEvmTokenId', type: 'bytes32' },
                    { name: 'externalAssetId', type: 'bytes32' },
                    { name: 'categoryId', type: 'bytes32' },
                    { name: 'marketplaceProvenanceRef', type: 'bytes32' },
                    { name: 'acquisitionPriceUsdt6', type: 'uint256' },
                    { name: 'currentValueUsdt6', type: 'uint256' },
                    { name: 'lastNavMarkUsdt6', type: 'uint256' },
                    { name: 'acquisitionDate', type: 'uint256' },
                    { name: 'lastValuationAt', type: 'uint256' },
                    { name: 'status', type: 'uint8' },
                    { name: 'metadataHash', type: 'bytes32' },
                    { name: 'proofHash', type: 'bytes32' },
                ],
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ name: 'chainEid', type: 'uint32' }],
        name: 'getChainSafe',
        outputs: [
            {
                components: [
                    { name: 'enabled', type: 'bool' },
                    { name: 'chainEid', type: 'uint32' },
                    { name: 'evmSafe', type: 'address' },
                    { name: 'nonEvmSafe', type: 'bytes32' },
                    { name: 'label', type: 'bytes32' },
                ],
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ name: 'marketplaceId', type: 'bytes32' }],
        name: 'isMarketplaceApproved',
        outputs: [{ name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ name: 'purchaseKey', type: 'bytes32' }],
        name: 'getPurchaseAuthorization',
        outputs: [
            {
                components: [
                    { name: 'purchaseKey', type: 'bytes32' },
                    { name: 'status', type: 'uint8' },
                    { name: 'chainEid', type: 'uint32' },
                    { name: 'marketplaceId', type: 'bytes32' },
                    { name: 'assetRef', type: 'bytes32' },
                    { name: 'fundingToken', type: 'address' },
                    { name: 'maxSpendUsdt6', type: 'uint256' },
                    { name: 'releasedUsdt6', type: 'uint256' },
                    { name: 'destinationSafe', type: 'address' },
                    { name: 'destinationSafeAlt', type: 'bytes32' },
                    { name: 'approvedAt', type: 'uint256' },
                    { name: 'mandateHash', type: 'bytes32' },
                    { name: 'executionRef', type: 'bytes32' },
                    { name: 'settlementRef', type: 'bytes32' },
                    { name: 'proofHash', type: 'bytes32' },
                ],
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ name: 'saleKey', type: 'bytes32' }],
        name: 'getSaleAuthorization',
        outputs: [
            {
                components: [
                    { name: 'saleKey', type: 'bytes32' },
                    { name: 'status', type: 'uint8' },
                    { name: 'positionId', type: 'uint256' },
                    { name: 'chainEid', type: 'uint32' },
                    { name: 'marketplaceId', type: 'bytes32' },
                    { name: 'minNetProceedsUsdt6', type: 'uint256' },
                    { name: 'grossProceedsUsdt6', type: 'uint256' },
                    { name: 'marketplaceFeesUsdt6', type: 'uint256' },
                    { name: 'bridgeFeesUsdt6', type: 'uint256' },
                    { name: 'netProceedsUsdt6', type: 'uint256' },
                    { name: 'sourceChainEid', type: 'uint32' },
                    { name: 'sourceToken', type: 'address' },
                    { name: 'sourceTokenAmount', type: 'uint256' },
                    { name: 'sourceTokenDecimals', type: 'uint8' },
                    { name: 'proceedsToken', type: 'address' },
                    { name: 'proceedsAmount', type: 'uint256' },
                    { name: 'approvedAt', type: 'uint256' },
                    { name: 'mandateHash', type: 'bytes32' },
                    { name: 'executionRef', type: 'bytes32' },
                    { name: 'proceedsRef', type: 'bytes32' },
                    { name: 'sourceProceedsRef', type: 'bytes32' },
                    { name: 'proofHash', type: 'bytes32' },
                ],
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
] as const;

export const COURTYARD_WORKFLOW_ABI = [
    {
        inputs: [
            { name: 'chainEid', type: 'uint32' },
            { name: 'evmSafe', type: 'address' },
            { name: 'nonEvmSafe', type: 'bytes32' },
            { name: 'label', type: 'bytes32' },
            { name: 'enabled', type: 'bool' },
        ],
        name: 'configureCourtyardChain',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'purchaseKey', type: 'bytes32' },
            { name: 'chainEid', type: 'uint32' },
            { name: 'assetRef', type: 'bytes32' },
            { name: 'maxSpendUsdt6', type: 'uint256' },
            { name: 'mandateHash', type: 'bytes32' },
        ],
        name: 'authorizeCourtyardPurchase',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ name: 'purchaseKey', type: 'bytes32' }, { name: 'amountUsdt6', type: 'uint256' }],
        name: 'releaseCourtyardPurchaseFunds',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'purchaseKey', type: 'bytes32' },
            { name: 'executionRef', type: 'bytes32' },
            { name: 'settlementRef', type: 'bytes32' },
            { name: 'proofHash', type: 'bytes32' },
        ],
        name: 'recordCourtyardPurchaseExecution',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'purchaseKey', type: 'bytes32' },
            {
                components: [
                    { name: 'custodyMode', type: 'uint8' },
                    { name: 'tokenStandard', type: 'bytes32' },
                    { name: 'evmCollection', type: 'address' },
                    { name: 'nonEvmCollection', type: 'bytes32' },
                    { name: 'tokenId', type: 'uint256' },
                    { name: 'nonEvmTokenId', type: 'bytes32' },
                    { name: 'externalAssetId', type: 'bytes32' },
                    { name: 'categoryId', type: 'bytes32' },
                    { name: 'marketplaceProvenanceRef', type: 'bytes32' },
                    { name: 'acquisitionPriceUsdt6', type: 'uint256' },
                    { name: 'metadataHash', type: 'bytes32' },
                    { name: 'proofHash', type: 'bytes32' },
                ],
                name: 'input',
                type: 'tuple',
            },
        ],
        name: 'recordCourtyardPosition',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'saleKey', type: 'bytes32' },
            { name: 'positionId', type: 'uint256' },
            { name: 'minNetProceedsUsdt6', type: 'uint256' },
            { name: 'mandateHash', type: 'bytes32' },
        ],
        name: 'authorizeCourtyardSale',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { name: 'saleKey', type: 'bytes32' },
            { name: 'grossProceedsUsdt6', type: 'uint256' },
            { name: 'marketplaceFeesUsdt6', type: 'uint256' },
            { name: 'bridgeFeesUsdt6', type: 'uint256' },
            { name: 'executionRef', type: 'bytes32' },
            { name: 'proceedsRef', type: 'bytes32' },
            { name: 'proofHash', type: 'bytes32' },
        ],
        name: 'recordCourtyardSaleExecution',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ name: 'saleKey', type: 'bytes32' }, { name: 'netProceedsUsdt6', type: 'uint256' }],
        name: 'confirmCourtyardSaleProceeds',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [{ name: 'saleKey', type: 'bytes32' }],
        name: 'finalizeCourtyardSale',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
] as const;

// Legacy aliases retained so older admin-only panels still typecheck even though
// the live admin app now targets the profit-participation surface.
export const FUND_V4_ABI = FUND_ADMIN_ABI;
export const STARGATE_ADAPTER_ABI = [
    {
        inputs: [
            { name: 'dstEid', type: 'uint32' },
            { name: 'token', type: 'address' },
            { name: 'amount', type: 'uint256' },
            { name: 'options', type: 'bytes' },
        ],
        name: 'quoteBridge',
        outputs: [{ name: 'nativeFee', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
] as const;
